[agent]
  debug = false
  interval = "5s"
  flush_interval = "5s"

# INPUT: Listening to Mosquitto
[[inputs.mqtt_consumer]]
  servers = ["tcp://project_broker:1883"]
  topics = ["home/livingroom/plug/power"]
  username = "ShellyPlug"
  password = "TestPass123"
  data_format = "value"
  data_type = "float"

# OUTPUT: Sending to InfluxDB
[[outputs.influxdb_v2]]
  urls = ["http://project_db:8086"]
  token = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"
